check50:
  checks:
    variables:
      - run: ./variables
        stdin: 8
        stdout: Right now I'm 8 years old./n Next year I'll be 9 years old./n In 10 years, I'll be 18!/n In 50 years, I'll be 58! Wow!/n
        exit: 0 # expect program to exit with exitcode 0
