check50: 
  files: &check50_files
    - !exclude "*"
    - !require ./apt1/bathroom/bathroom_cabinet/bathroom_cabinet.txt
    ./apt1/kitchen/cabinet/cabinet_contents.txt
  checks: checks.py
submit50:
  files: *check50_files
